### ISSUE TITLE
Blank page issue

### ISSUE THREAD

**Issue by 5iwek** [Salmen2/Simple-Faucet-Script#16]
Hello. It's been a few days since I uploaded the faucet files on my server, and for the whole time I've been trying to fix the issue with the blank pages. I did everything correctly, I've also switched from PHP 7.0 to 5.6, it's still not working. I've bought a few hosting accounts from different operators, even a VPS server, but the issue still remains. Can you help me with that?

**Comment by Salmen2** [comment]
Hello,
Please replace in core.php the third line with
`error_reporting(E_ALL);`
then save it and open the faucet in your browser again. You should be able to see the issue.

**Comment by edennede** [comment]
Hello, 

I have tje same error.
I have remplaced  in core.php the third line witherror_reporting(E_ALL);
But now I have that : 


Notice: Undefined index: address in /storage/ssd5/243/12989243/public_html/includes/session.php on line 2

Warning: preg_replace_callback(): Requires argument 2, '', to be a valid callback in /storage/ssd5/243/12989243/public_html/includes/template.class.php on line 95

Notice: Undefined variable: navBarLinks in /storage/ssd5/243/12989243/public_html/includes/template.settings.php on line 40

Fatal error: Uncaught Exception: GMP extension seems not to be installed in /storage/ssd5/243/12989243/public_html/includes/blockio.library.php:10 Stack trace: #0 /storage/ssd5/243/12989243/public_html/includes/core.php(11): include() #1 /storage/ssd5/243/12989243/public_html/index.php(2): include('/storage/ssd5/2...') #2 {main} thrown in /storage/ssd5/243/12989243/public_html/includes/blockio.library.php on line 10


How can i fix it ?
Thx

**Comment by Salmen2** [comment]
> Hello,
> 
> I have the same error.
> I have remplaced in core.php the third line witherror_reporting(E_ALL);
> But now I have that :
> 
> Notice: Undefined index: address in /storage/ssd5/243/12989243/public_html/includes/session.php on line 2
> 
> Warning: preg_replace_callback(): Requires argument 2, '', to be a valid callback in /storage/ssd5/243/12989243/public_html/includes/template.class.php on line 95
> 
> Notice: Undefined variable: navBarLinks in /storage/ssd5/243/12989243/public_html/includes/template.settings.php on line 40
> 
> Fatal error: Uncaught Exception: GMP extension seems not to be installed in /storage/ssd5/243/12989243/public_html/includes/blockio.library.php:10 Stack trace: #0 /storage/ssd5/243/12989243/public_html/includes/core.php(11): include() #1 /storage/ssd5/243/12989243/public_html/index.php(2): include('/storage/ssd5/2...') #2 {main} thrown in /storage/ssd5/243/12989243/public_html/includes/blockio.library.php on line 10
> 
> How can i fix it ?
> Thx

The extension PHP-GMP is required. Please install it/enable it.

**Comment by Salmen2** [comment]
> I managed to fix the error 500 by reinstalling GMP, but now I'm facing the same problem that I described in my first post. It doesn't show any error report after replacing the third line of core.php.

Is error_reporting enabled by default in PHP configuration file?

**Comment by edennede** [comment]
> s error_reporting enabled by default in PHP configuration file?
Now, I have error 500, iIn the core.php file error_reporting is on error_reporting(E_ALL);

**Comment by edennede** [comment]
> > J'ai réussi à corriger l'erreur 500 en réinstallant GMP, mais maintenant je suis confronté au même problème que celui décrit dans mon premier post. Il ne montre aucun rapport d'erreur après avoir remplacé la troisième ligne de core.php.
> 
> Est-ce que error_reporting est activé par défaut dans le fichier de configuration PHP?

Now, I have too error 500, in the core.php file error_reporting is on error_reporting(E_ALL);

**Comment by Salmen2** [comment]
> > > J'ai réussi à corriger l'erreur 500 en réinstallant GMP, mais maintenant je suis confronté au même problème que celui décrit dans mon premier post. Il ne montre aucun rapport d'erreur après avoir remplacé la troisième ligne de core.php.
> > 
> > 
> > Est-ce que error_reporting est activé par défaut dans le fichier de configuration PHP?
> 
> Now, I have too error 500, in the core.php file error_reporting is on error_reporting(E_ALL);
> 
> How can I fix it ?

Have you installed the required packages?

**Comment by edennede** [comment]
> > > > J'ai réussi à corriger l'erreur 500 en réinstallant GMP, mais maintenant je suis confronté au même problème que celui décrit dans mon premier post. Il ne montre aucun rapport d'erreur après avoir remplacé la troisième ligne de core.php.
> > > 
> > > 
> > > Est-ce que error_reporting est activé par défaut dans le fichier de configuration PHP?
> > 
> > 
> > Now, I have too error 500, in the core.php file error_reporting is on error_reporting(E_ALL);
> > How can I fix it ?
> 
> Have you installed the required packages?

Yes GMP-PHP is installed.

**Comment by Salmen2** [comment]
> > > > > J'ai réussi à corriger l'erreur 500 en réinstallant GMP, mais maintenant je suis confronté au même problème que celui décrit dans mon premier post. Il ne montre aucun rapport d'erreur après avoir remplacé la troisième ligne de core.php.
> > > > 
> > > > 
> > > > Est-ce que error_reporting est activé par défaut dans le fichier de configuration PHP?
> > > 
> > > 
> > > Now, I have too error 500, in the core.php file error_reporting is on error_reporting(E_ALL);
> > > How can I fix it ?
> > 
> > 
> > Have you installed the required packages?
> 
> Yes GMP-PHP is installed.

Hi,
Can you upload this file (https://github.com/Salmen2/Simple-Faucet-Script/blob/master/install.php) to your faucet's directory and then visit the page?
