### ISSUE TITLE
Join button doesn't work

### ISSUE THREAD

**Issue by 5iwek** [Salmen2/Simple-Faucet-Script#20]
Hi. The "join" button doesn't seem to work, it just reloads the page.

**Comment by 5iwek** [comment]
Take a look yourself: http://51.75.76.67/

**Comment by Salmen2** [comment]
Does the MySQL table 'faucet_user_list' have any entries?

**Comment by 5iwek** [comment]
No, it's empty.

**Comment by Salmen2** [comment]
Ok, have you pointed to the correct database in the config.php file?

**Comment by 5iwek** [comment]
Yes, I'm positive it's correct

**Comment by 5iwek** [comment]
https://i.imgur.com/mpGwx9E.png
As you can see, there is no issue with database connection

**Comment by Salmen2** [comment]
Ok, which kind of MySQL connection data do you use, the root?

**Comment by 5iwek** [comment]
No. I created a user and granted all privileges, *.*

**Comment by Salmen2** [comment]
Ok, there's something fishy. Do you have Discord or Skype, so we can discuss this issue in detail there?

**Comment by 5iwek** [comment]
I do have discord. Filip#3515

**Comment by Salmen2** [comment]
Fixed with commit https://github.com/Salmen2/Simple-Faucet-Script/commit/54665b127102e60f43ff1ab4577cc8071fd6c76b
