### ISSUE TITLE
Install PHP-GMP.

### ISSUE THREAD

**Issue by yearny** [Salmen2/Simple-Faucet-Script#21]
I uploaded everything on the SFTP-Server and added SQL. But when I open /install.php on my website there is the comment ,,GMP is not installed. Please install PHP-GMP.'' What can I do? I don't have Linux/Ubuntu, I just have a Windows computer and a webspace online.

**Comment by Salmen2** [comment]
A quick search on Google gives this result to your solution: https://stackoverflow.com/questions/44448409/xampp-windows-php-gmp-functions/50244817
Simply uncomment the following in php.ini
`;extension=php_gmp.dll`
