### ISSUE TITLE
new withdrawal method

### ISSUE THREAD

**Issue by Pi-Github16** [Salmen2/Simple-Faucet-Script#23]
Please add manual withdrawal in the script.

**Comment by Akashgormani** [comment]
> Please add manual withdrawal in the script.

i can add, also i can add shortlinks.
Contact discord: Learn2Earn18#7304

**Comment by Pi-Github16** [comment]
no update?, I'm always waiting for a new addon to appear 🙄

Please add new captcha.. recaptcha it makes me crazy...
