### ISSUE TITLE
short link problems

### ISSUE THREAD

**Issue by criptopobre** [Salmen2/Simple-Faucet-Script#25]
I made the purchase of the short links through the site but after the installation on my faucet is not functional, I installed it as described in the tutorial but when the user completes the entire procedure in addition to not returning to the site, it does not account for the value in the user's account , I need to solve this problem

**Comment by Salmen2** [comment]
May you send a link of your faucet?

**Comment by criptopobre** [comment]
https://freebtc.space/

Good morning, follow the tap link above.

Em ter, 7 de jun de 2022 08:53, Salmen2 ***@***.***> escreveu:

**Comment by Salmen2** [comment]
It looks like you forgot to add your URL in includes/config.php

**Comment by criptopobre** [comment]
in the tutorial does not send add the link inside the cpanel, in which case
I need to add which link and in which location?  could you help me with
this?

Em ter, 7 de jun de 2022 09:47, Salmen2 ***@***.***> escreveu:

**Comment by Salmen2** [comment]
You need to set the URL in the configuration file of the script. It's in the directory _includes_ and file _config.php_

**Comment by criptopobre** [comment]
I really need your support, I'm waiting for a brief tutorial from you,
thank you in advance

Em ter, 7 de jun de 2022 10:14, CRIPTO PB ***@***.***> escreveu:

**Comment by Salmen2** [comment]
In this directory, _includes_
![image](https://user-images.githubusercontent.com/15948787/172431523-8777b714-ae70-4081-a6c4-962610c3d0f0.png)
you will find the file _config.php_. In this file, you need to insert your link to the faucet as follows
![image](https://user-images.githubusercontent.com/15948787/172431900-9dfea9fc-2cd4-4f71-9b12-cd740e63855a.png)

**Comment by criptopobre** [comment]
I did this procedure on the day of installing the script, so this is not the problem, what other possible problem would be and how could I solve it

**Comment by Salmen2** [comment]
I figured out the issue. It needs to do a cleaning
Thereby, access PHPMyAdmin in cPanel
![image](https://user-images.githubusercontent.com/15948787/172610468-ab85cb6f-5356-4c93-a788-91b9f82e9e66.png)
Go to the database of the faucet and click on the top 'SQL' and run the following SQL command
`TRUNCATE TABLE `faucet_addon_shortlinks_views``

This clears all generated links and you should be able to pass the exe.io short link back to your faucet.

**Comment by criptopobre** [comment]
the problem was solved successfully, thank you very much for the excellent support

**Comment by criptopobre** [comment]
To end our contact I would like to make some suggestions. add other paid extensions like pay to click page, offers among others, I would buy everything myself to expand my business.

**Comment by criptopobre** [comment]
the URL you say and the link of the shortener or the URL of my site, I'm
not able to understand very well, could you give me a step by step on how
to do it?

Em ter, 7 de jun de 2022 10:00, Salmen2 ***@***.***> escreveu:

**Comment by Salmen2** [comment]
> not able to understand very well, could you give me a step by step on how

This is the general configuration file of your faucet, there needs to be the link/URL to your faucet.
