### ISSUE TITLE
HTTP ERROR 500 AFTER INSTALLATION

### ISSUE THREAD

**Issue by Ozimuzor** [Salmen2/Simple-Faucet-Script#29]
I am getting HTTP ERROR 500 after following the installation guide. I didn't miss anything. Please help.

**Comment by Salmen2** [comment]
What kind of PHP version do you use?

**Comment by Ozimuzor** [comment]
I used 8.1 the last time

**Comment by Salmen2** [comment]
PHP 500 usually indicates that there is an error. It also means that you're not able to see the error. Please check that display_errors is turned to ON. Furthermore, please change in includes/core.php the following line
`error_reporting(0);`
to
`error_reporting(E_ALL);`

**Comment by Ozimuzor** [comment]
![Screenshot_20230426_001951](https://user-images.githubusercontent.com/97916093/234428170-011146bc-fd57-4ee4-b3e0-4ec5809870e0.png)
Here is the displayed error.

**Comment by Salmen2** [comment]
Apparently, you did not have imported sql.sql into your database

**Comment by Ozimuzor** [comment]
Successfully imported but the error continues. Is there any other way to fix this?

**Comment by Ozimuzor** [comment]
![Screenshot_20230426_113926](https://user-images.githubusercontent.com/97916093/234551163-63a72876-66e5-4825-96be-2fcf3617957c.png)
I have managed to fix the former error. This is what I get from both user end and admin end.

**Comment by Ozimuzor** [comment]
Thank, bro.

**Comment by Salmen2** [comment]
You may want to set error_reporting to
`error_reporting(E_ALL);`

**Comment by Ozimuzor** [comment]
![Screenshot_20230426_151634](https://user-images.githubusercontent.com/97916093/234604325-8728519e-2887-4f90-95ea-03b6df64aad2.png)
Here are the displayed errors.

**Comment by Salmen2** [comment]
Which error do you get above when you log in with any crypto address?
